num1 = int(input("Pick a number: "))
num2 = int(input("Pick another number: "))
num3 = int(input("Pick another number: "))
num4 = int(input("Pick another number: "))
result = (num1 * num2 * num3 * num4)
print("The product of " + str(num1) + " * " + str(num2) + " * " + str(num3) + " * " + str(num4) + " is " + str(result))